# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestEdit():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_edit(self):
    # Test name: edit
    # Step # | name | target | value
    # 1 | open | / | 
    self.driver.get("http://app.xunjietupian.com/")
    # 2 | setWindowSize | 1552x840 | 
    self.driver.set_window_size(1552, 840)
    # 3 | click | css=.raw:nth-child(3) > a:nth-child(7) > .fl | 
    self.driver.find_element(By.CSS_SELECTOR, ".raw:nth-child(3) > a:nth-child(7) > .fl").click()
    # 4 | click | css=.btn-first-load | 
    # self.driver.find_element(By.CSS_SELECTOR, ".btn-first-load").click()
    # 5 | type | css=.tui-image-editor-load-btn | /
    # self.driver.find_element(By.CSS_SELECTOR, ".tui-image-editor-load-btn").send_keys("/")
    upload = self.driver.find_element(By.CSS_SELECTOR, ".tui-image-editor-load-btn")
    time.sleep(1)
    upload.send_keys("E:/code/PycharmProjects/Test2/img/test.jpg")
    time.sleep(1)
    # 6 | click | css=.color-picker-draw > .fl:nth-child(1) | 
    self.driver.find_element(By.CSS_SELECTOR, ".color-picker-draw > .fl:nth-child(1)").click()
    # 7 | mouseDownAt | css=.upper-canvas | 708.3999938964844,66.39999389648438
    element = self.driver.find_element(By.CSS_SELECTOR, ".upper-canvas")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).move_by_offset(-200,-200).click_and_hold().move_by_offset(100,0).release().perform()
    # 8 | mouseMoveAt | css=.upper-canvas | 708.3999938964844,66.39999389648438
    # element = self.driver.find_element(By.CSS_SELECTOR, ".upper-canvas")
    # actions = ActionChains(self.driver)
    # actions.move_to_element(element).perform()
    # 9 | mouseUpAt | css=.upper-canvas | 708.3999938964844,66.39999389648438
    # element = self.driver.find_element(By.CSS_SELECTOR, ".upper-canvas")
    # actions = ActionChains(self.driver)
    # actions.move_to_element(element).release().perform()
    # 10 | click | css=.upper-canvas | 
    self.driver.find_element(By.CSS_SELECTOR, ".upper-canvas").click()
    # 11 | click | css=.btn-func-shape > p | 
    self.driver.find_element(By.CSS_SELECTOR, ".btn-func-shape > p").click()
    # 12 | click | css=.color-picker-shape > .fl:nth-child(4) | 
    self.driver.find_element(By.CSS_SELECTOR, ".color-picker-shape > .fl:nth-child(4)").click()
    # 13 | mouseDownAt | css=.upper-canvas | 316.3999938964844,226.39999389648438
    element = self.driver.find_element(By.CSS_SELECTOR, ".upper-canvas")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).click_and_hold().move_by_offset(100,100).release().perform()
    # 14 | mouseMoveAt | css=.upper-canvas | 316.3999938964844,226.39999389648438
    # element = self.driver.find_element(By.CSS_SELECTOR, ".upper-canvas")
    # actions = ActionChains(self.driver)
    # actions.move_to_element(element).perform()
    # 15 | mouseUpAt | css=.upper-canvas | 316.3999938964844,226.39999389648438
    # element = self.driver.find_element(By.CSS_SELECTOR, ".upper-canvas")
    # actions = ActionChains(self.driver)
    # actions.move_to_element(element).release().perform()
    # 16 | click | css=.upper-canvas | 
    self.driver.find_element(By.CSS_SELECTOR, ".upper-canvas").click()
    # 17 | click | css=.btn-func-text > p | 
    self.driver.find_element(By.CSS_SELECTOR, ".btn-func-text > p").click()
    # 18 | click | css=.upper-canvas | 
    self.driver.find_element(By.CSS_SELECTOR, ".upper-canvas").click()
    # 19 | mouseDownAt | css=.upper-canvas | 556.3999938964844,262.3999938964844
    element = self.driver.find_element(By.CSS_SELECTOR, ".upper-canvas")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).click_and_hold().perform()
    # 20 | mouseMoveAt | css=.upper-canvas | 556.3999938964844,262.3999938964844
    element = self.driver.find_element(By.CSS_SELECTOR, ".upper-canvas")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    # 21 | mouseUpAt | css=.upper-canvas | 556.3999938964844,262.3999938964844
    element = self.driver.find_element(By.CSS_SELECTOR, ".upper-canvas")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).release().perform()
    # 22 | click | css=.upper-canvas | 
    # self.driver.find_element(By.CSS_SELECTOR, ".upper-canvas").click()
    # 23 | click | css=.upper-canvas | 
    # self.driver.find_element(By.CSS_SELECTOR, ".upper-canvas").click()
    # 24 | click | css=.upper-canvas | 
    # self.driver.find_element(By.CSS_SELECTOR, ".upper-canvas").click()
    # 25 | doubleClick | css=.upper-canvas | 
    element = self.driver.find_element(By.CSS_SELECTOR, ".upper-canvas")
    actions = ActionChains(self.driver)
    actions.double_click(element).perform()
    # 26 | type | css=.tui-image-eidtor-textarea | Test
    self.driver.find_element(By.CSS_SELECTOR, ".tui-image-eidtor-textarea").send_keys("Test")
    # 27 | click | css=.btn-func-crop > p | 
    self.driver.find_element(By.CSS_SELECTOR, ".btn-func-crop > p").click()
    # 28 | mouseDownAt | css=.upper-canvas | 978.3999938964844,482.3999938964844
    element = self.driver.find_element(By.CSS_SELECTOR, ".upper-canvas")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).click_and_hold().perform()
    # 29 | mouseMoveAt | css=.upper-canvas | 978.3999938964844,482.3999938964844
    element = self.driver.find_element(By.CSS_SELECTOR, ".upper-canvas")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    # 30 | mouseUpAt | css=.upper-canvas | 978.3999938964844,482.3999938964844
    element = self.driver.find_element(By.CSS_SELECTOR, ".upper-canvas")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).release().perform()
    # 31 | click | css=.upper-canvas | 
    self.driver.find_element(By.CSS_SELECTOR, ".upper-canvas").click()
    # 32 | click | css=.btn-crop-apply | 
    self.driver.find_element(By.CSS_SELECTOR, ".btn-crop-apply").click()
    # 33 | click | css=.btn-func-rotate > p | 
    self.driver.find_element(By.CSS_SELECTOR, ".btn-func-rotate > p").click()
    # 34 | click | css=.btn-rotate-cw > img | 
    self.driver.find_element(By.CSS_SELECTOR, ".btn-rotate-cw > img").click()
    # 35 | click | css=.btn-func-flip > p | 
    self.driver.find_element(By.CSS_SELECTOR, ".btn-func-flip > p").click()
    # 36 | click | css=.btn-flip-x > img | 
    self.driver.find_element(By.CSS_SELECTOR, ".btn-flip-x > img").click()
    # 37 | click | css=.btn-down-load | 
    self.driver.find_element(By.CSS_SELECTOR, ".btn-down-load").click()
    # 38 | close |  |
    time.sleep(2)
    self.driver.close()
  
