# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestFilter():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_filter(self):
    # Test name: filter
    # Step # | name | target | value
    # 1 | open | / | 
    self.driver.get("http://app.xunjietupian.com/")
    # 2 | setWindowSize | 1056x808 | 
    self.driver.set_window_size(1056, 808)
    # 3 | mouseOver | css=.raw:nth-child(1) > a:nth-child(3) > .fl | 
    element = self.driver.find_element(By.CSS_SELECTOR, ".raw:nth-child(1) > a:nth-child(3) > .fl")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    # 4 | click | css=.raw:nth-child(3) > a:nth-child(1) img | 
    self.driver.find_element(By.CSS_SELECTOR, ".raw:nth-child(3) > a:nth-child(1) img").click()
    # 5 | click | css=.btn-first-load | 
    # self.driver.find_element(By.CSS_SELECTOR, ".btn-first-load").click()
    # 6 | type | css=.tui-image-editor-load-btn | /
    # self.driver.find_element(By.CSS_SELECTOR, ".tui-image-editor-load-btn").send_keys("/")
    upload = self.driver.find_element(By.CSS_SELECTOR, ".tui-image-editor-load-btn")
    time.sleep(1)
    upload.send_keys("E:/code/PycharmProjects/Test2/img/test.jpg")
    time.sleep(1)
    # 7 | click | css=.menu-filter > .fl:nth-child(2) | 
    self.driver.find_element(By.CSS_SELECTOR, ".menu-filter > .fl:nth-child(2)").click()
    # 8 | click | css=.btn-down-load | 
    self.driver.find_element(By.CSS_SELECTOR, ".btn-down-load").click()
    # 9 | click | css=.menu-filter > .fl:nth-child(3) | 
    self.driver.find_element(By.CSS_SELECTOR, ".menu-filter > .fl:nth-child(3)").click()
    # 10 | click | css=.btn-down-load | 
    self.driver.find_element(By.CSS_SELECTOR, ".btn-down-load").click()
    # 11 | click | css=.menu-filter > .fl:nth-child(4) | 
    self.driver.find_element(By.CSS_SELECTOR, ".menu-filter > .fl:nth-child(4)").click()
    # 12 | click | css=.btn-down-load | 
    self.driver.find_element(By.CSS_SELECTOR, ".btn-down-load").click()
    # 13 | click | css=.menu-filter > .fl:nth-child(5) | 
    self.driver.find_element(By.CSS_SELECTOR, ".menu-filter > .fl:nth-child(5)").click()
    # 14 | click | css=.btn-down-load | 
    self.driver.find_element(By.CSS_SELECTOR, ".btn-down-load").click()
    # 15 | close |  |
    time.sleep(2)
    self.driver.close()
  
