# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestRotate():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_rotate(self):
    # Test name: rotate
    # Step # | name | target | value
    # 1 | open | / | 
    self.driver.get("http://app.xunjietupian.com/")
    # 2 | setWindowSize | 1552x840 | 
    self.driver.set_window_size(1552, 840)
    # 3 | click | css=.raw:nth-child(3) > a:nth-child(3) img | 
    self.driver.find_element(By.CSS_SELECTOR, ".raw:nth-child(3) > a:nth-child(3) img").click()
    # 4 | click | css=.btn-first-load | 
    # self.driver.find_element(By.CSS_SELECTOR, ".btn-first-load").click()
    # 5 | type | css=.tui-image-editor-load-btn | /
    # self.driver.find_element(By.CSS_SELECTOR, ".tui-image-editor-load-btn").send_keys("/")
    upload = self.driver.find_element(By.CSS_SELECTOR, ".tui-image-editor-load-btn")
    time.sleep(1)
    upload.send_keys("E:/code/PycharmProjects/Test2/img/test.jpg")
    time.sleep(1)
    # 6 | click | css=.btn-rotate-ccw > img | 
    self.driver.find_element(By.CSS_SELECTOR, ".btn-rotate-ccw > img").click()
    # 7 | click | css=.btn-down-load | 
    self.driver.find_element(By.CSS_SELECTOR, ".btn-down-load").click()
    # 8 | click | css=.btn-rotate-cw > img | 
    self.driver.find_element(By.CSS_SELECTOR, ".btn-rotate-cw > img").click()
    # 9 | click | css=.btn-rotate-cw > img | 
    self.driver.find_element(By.CSS_SELECTOR, ".btn-rotate-cw > img").click()
    # 10 | click | css=.btn-down-load | 
    self.driver.find_element(By.CSS_SELECTOR, ".btn-down-load").click()
    # 11 | type | css=.range-rotate-full | 96
    self.driver.find_element(By.CSS_SELECTOR, ".range-rotate-full").send_keys("96")
    # 12 | click | css=.range-rotate-full | 
    self.driver.find_element(By.CSS_SELECTOR, ".range-rotate-full").click()
    # 13 | click | css=.btn-down-load | 
    self.driver.find_element(By.CSS_SELECTOR, ".btn-down-load").click()
    # 14 | close |  |
    time.sleep(2)
    self.driver.close()
  
